 services:
  - type: web
    name: vocaband
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: ALLOWED_ORIGIN
        value: https://www.vocaband.com
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
