import { useState } from "react";

/**
 * The assignment-builder form fields plus the Smart Paste dialog state:
 * title, deadline, chosen modes, generated sentences (+ their difficulty and
 * the auto-generated flag), the wizard step, and the paste-import scratch
 * state (raw text, dialog visibility, match counts, tag input, topic-pack
 * sheet). They drive one authoring flow and clear together when the teacher
 * finishes or cancels, so they live behind a single hook.
 */
export function useAssignmentBuilderState() {
  const [assignmentTitle, setAssignmentTitle] = useState("");
  const [assignmentDeadline, setAssignmentDeadline] = useState("");
  const [assignmentModes, setAssignmentModes] = useState<string[]>([]);
  const [assignmentSentences, setAssignmentSentences] = useState<string[]>([]);
  const [sentenceDifficulty, setSentenceDifficulty] = useState<1 | 2 | 3 | 4>(2);
  const [sentencesAutoGenerated, setSentencesAutoGenerated] = useState(false);
  const [, setAssignmentStep] = useState(1);

  // --- SMART PASTE STATE ---
  const [pastedText, setPastedText] = useState("");
  const [showPasteDialog, setShowPasteDialog] = useState(false);
  const [pasteMatchedCount, setPasteMatchedCount] = useState(0);
  const [pasteUnmatched, setPasteUnmatched] = useState<string[]>([]);
  const [tagInput, setTagInput] = useState("");
  const [showTopicPacks, setShowTopicPacks] = useState(false);

  return {
    assignmentTitle, setAssignmentTitle,
    assignmentDeadline, setAssignmentDeadline,
    assignmentModes, setAssignmentModes,
    assignmentSentences, setAssignmentSentences,
    sentenceDifficulty, setSentenceDifficulty,
    sentencesAutoGenerated, setSentencesAutoGenerated,
    setAssignmentStep,
    pastedText, setPastedText,
    showPasteDialog, setShowPasteDialog,
    pasteMatchedCount, setPasteMatchedCount,
    pasteUnmatched, setPasteUnmatched,
    tagInput, setTagInput,
    showTopicPacks, setShowTopicPacks,
  };
}
