import { useState } from "react";

/**
 * The assignment-builder form fields: title, deadline, chosen modes, generated
 * sentences (+ their difficulty and the auto-generated flag), the wizard step,
 * and the topic-pack sheet toggle. They drive one authoring flow and clear
 * together when the teacher finishes or cancels, so they live behind a single
 * hook.
 */
export function useAssignmentBuilderState() {
  const [assignmentTitle, setAssignmentTitle] = useState("");
  const [assignmentDeadline, setAssignmentDeadline] = useState("");
  const [assignmentModes, setAssignmentModes] = useState<string[]>([]);
  const [assignmentSentences, setAssignmentSentences] = useState<string[]>([]);
  const [sentenceDifficulty, setSentenceDifficulty] = useState<1 | 2 | 3 | 4>(2);
  const [sentencesAutoGenerated, setSentencesAutoGenerated] = useState(false);
  const [, setAssignmentStep] = useState(1);
  const [showTopicPacks, setShowTopicPacks] = useState(false);

  return {
    assignmentTitle, setAssignmentTitle,
    assignmentDeadline, setAssignmentDeadline,
    assignmentModes, setAssignmentModes,
    assignmentSentences, setAssignmentSentences,
    sentenceDifficulty, setSentenceDifficulty,
    sentencesAutoGenerated, setSentencesAutoGenerated,
    setAssignmentStep,
    showTopicPacks, setShowTopicPacks,
  };
}
