/**
 * useAssignmentAutoPopulate — two teacher-authoring effects that
 * populate the assignment builder's state based on teacher input.
 *
 *   1. Sentence Builder auto-generate.  When the teacher selects
 *      Sentence Builder as one of the assignment modes, we generate
 *      practice sentences from their chosen words automatically so
 *      they don't have to hand-author every one.  Re-runs when
 *      words, modes, or difficulty change, but NOT when the teacher
 *      has manually edited the sentences (tracked by
 *      `sentencesAutoGenerated`).  Clearing the word list also
 *      clears the sentences so the UI doesn't show stale ones.
 *
 *   2. Quick Play exact-match auto-add.  In the Quick Play setup
 *      view, when the teacher types an exact match for a word in
 *      the database, it's auto-added to the Quick Play selection.
 *      Partial matches (startsWith) are shown but NOT auto-added —
 *      only exact matches.  Deduped against existing selection.
 *
 * Both effects touch teacher-side assignment-authoring state and
 * follow the same "observe input → derive output" shape, so they
 * pair naturally.  The hook is write-only into App state — it
 * doesn't expose anything back to the caller.
 */
import { useEffect } from 'react';
import { ALL_WORDS, type Word } from '../data/vocabulary';
import { generateSentencesForAssignment } from '../data/sentence-bank';
import type { View } from '../core/views';

export interface UseAssignmentAutoPopulateParams {
  // Assignment builder state (read)
  view: View;
  assignmentModes: string[];
  selectedWords: number[];
  selectedWordsSet: Set<number>;
  customWords: Word[];
  sentenceDifficulty: 1 | 2 | 3 | 4;
  sentencesAutoGenerated: boolean;
  assignmentSentences: string[];

  // Quick Play setup state (read)
  searchTerms: string[];

  // Setters (write)
  setAssignmentSentences: React.Dispatch<React.SetStateAction<string[]>>;
  setSentencesAutoGenerated: React.Dispatch<React.SetStateAction<boolean>>;
  setQuickPlaySelectedWords: React.Dispatch<React.SetStateAction<Word[]>>;
}

export function useAssignmentAutoPopulate(
  params: UseAssignmentAutoPopulateParams,
): void {
  const {
    view,
    assignmentModes, selectedWords, selectedWordsSet, customWords,
    sentenceDifficulty, sentencesAutoGenerated, assignmentSentences,
    searchTerms,
    setAssignmentSentences, setSentencesAutoGenerated, setQuickPlaySelectedWords,
  } = params;

  // ─── 1. Sentence Builder + Fill-in-the-Blank auto-generate ────────
  // Both modes consume `assignment.sentences[]`.  Auto-generate template
  // sentences when either is selected so the teacher doesn't have to
  // hand-author every one.  AI generation is still opt-in via the
  // "Generate AI Sentences" button.
  useEffect(() => {
    if (
      !assignmentModes.includes('sentence-builder') &&
      !assignmentModes.includes('fill-blank')
    ) return;
    if (selectedWords.length === 0) {
      setAssignmentSentences([]);
      setSentencesAutoGenerated(false);
      return;
    }
    // Only auto-generate if the user hasn't manually edited (but always
    // regenerate on difficulty change).
    if (!sentencesAutoGenerated && assignmentSentences.length > 0) return;
    const allPossibleWords = [...ALL_WORDS, ...customWords];
    const uniqueWords = Array.from(new Map(allPossibleWords.map(w => [w.id, w])).values());
    const words = uniqueWords.filter(w => selectedWordsSet.has(w.id));
    const generated = generateSentencesForAssignment(words, sentenceDifficulty);
    setAssignmentSentences(generated);
    setSentencesAutoGenerated(true);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedWords, assignmentModes, sentenceDifficulty]);

  // ─── 2. Quick Play: auto-add exact matches to selection ───────────
  useEffect(() => {
    if (view !== 'quick-play-setup') return;

    // Exact matches only — startsWith / partial matches are shown in
    // the UI but NOT auto-added.
    const exactMatches: Word[] = [];
    searchTerms.forEach(term => {
      const exactMatchesForTerm = ALL_WORDS.filter(
        w => w.english.toLowerCase() === term,
      );
      exactMatches.push(...exactMatchesForTerm);
    });

    const uniqueExactMatches = Array.from(
      new Map(exactMatches.map(w => [w.id, w])).values(),
    );

    if (uniqueExactMatches.length > 0) {
      setQuickPlaySelectedWords(prev => {
        const existingIds = new Set(prev.map(w => w.id));
        const newWords = uniqueExactMatches.filter(w => !existingIds.has(w.id));
        return [...prev, ...newWords];
      });
    }
  }, [searchTerms, view, setQuickPlaySelectedWords]);
}
