/**
 * Regression tests for the shared Edit / Duplicate loader that seeds the
 * create-assignment wizard (handlers/teacherDashboardActions).
 *
 * Two bugs are covered:
 *
 * 1. DUPLICATE OVERWROTE THE ORIGINAL. The loader set `editingAssignment`
 *    for BOTH paths, and handleSaveAssignment branches on that value to
 *    `UPDATE ... .eq('id', editingAssignment.id)`. So "Duplicate" renamed
 *    the source row to "… (copy)" and replaced its word list instead of
 *    inserting a copy — the original was silently destroyed and no new
 *    assignment appeared. Only a real edit may carry the row identity.
 *
 * 2. COLD-VOCABULARY MISCLASSIFICATION. Custom words were detected purely
 *    by absence from ALL_WORDS. The vocabulary chunk loads lazily, so when
 *    a teacher hit Edit before it landed, `allWords` was [] and every
 *    curriculum word looked "unknown": they were all filed as custom and
 *    the picker was forced to the Custom tier.
 */
import { describe, expect, it, vi } from 'vitest';
import { loadAssignmentIntoCreateForm } from '../handlers/teacherDashboardActions';
import type { Word } from '../data/vocabulary';
import type { AssignmentData, ClassData } from '../core/supabase';

const CURRICULUM: Word[] = [
  { id: 1, english: 'apple', hebrew: 'תפוח', arabic: 'تفاحة', level: 'Set 1' },
  { id: 2, english: 'book', hebrew: 'ספר', arabic: 'كتاب', level: 'Set 1' },
  { id: 3, english: 'chair', hebrew: 'כיסא', arabic: 'كرسي', level: 'Set 2' },
] as unknown as Word[];

const OCR_CUSTOM = {
  id: -101, english: 'photosynthesis', hebrew: 'פוטוסינתזה', arabic: '—', level: 'Custom',
} as unknown as Word;

/** The vocabulary library mints POSITIVE synthetic ids (1e8 + |hash|). */
const LIBRARY_CUSTOM = {
  id: 100_000_042, english: 'mitochondria', hebrew: 'מיטוכונדריה', arabic: '—', level: 'Custom',
} as unknown as Word;

const CLASS = { id: 'class-1', name: 'Z7', code: '4ZSFLQZ9' } as unknown as ClassData;

function makeDeps(allWords: Word[]) {
  return {
    allWords,
    set1Words: CURRICULUM.filter((w) => w.level === 'Set 1'),
    setEditingAssignment: vi.fn(),
    setSelectedWords: vi.fn(),
    setCustomWords: vi.fn(),
    setAssignmentTitle: vi.fn(),
    setAssignmentDeadline: vi.fn(),
    setAssignmentModes: vi.fn(),
    setAssignmentSentences: vi.fn(),
    setSentenceDifficulty: vi.fn(),
    setSentencesAutoGenerated: vi.fn(),
    setSelectedLevel: vi.fn(),
    setSelectedClass: vi.fn(),
    setView: vi.fn(),
  };
}

function makeAssignment(over: Partial<AssignmentData> = {}): AssignmentData {
  return {
    id: 'assign-1',
    classId: 'class-1',
    title: 'Flashcards + Matching',
    wordIds: [1, 2, 3],
    words: CURRICULUM,
    allowedModes: ['classic'],
    deadline: null,
    sentences: [],
    ...over,
  } as unknown as AssignmentData;
}

describe('loadAssignmentIntoCreateForm — duplicate must not overwrite the original', () => {
  it('does NOT carry the source row identity when duplicating', () => {
    const deps = makeDeps(CURRICULUM);
    loadAssignmentIntoCreateForm(makeAssignment(), CLASS, true, deps);
    // null => handleSaveAssignment takes the INSERT branch and creates a copy.
    expect(deps.setEditingAssignment).toHaveBeenCalledWith(null);
    expect(deps.setAssignmentTitle).toHaveBeenCalledWith('Flashcards + Matching (copy)');
  });

  it('DOES carry the row identity for a real edit', () => {
    const deps = makeDeps(CURRICULUM);
    const assignment = makeAssignment();
    loadAssignmentIntoCreateForm(assignment, CLASS, false, deps);
    expect(deps.setEditingAssignment).toHaveBeenCalledWith(assignment);
    expect(deps.setAssignmentTitle).toHaveBeenCalledWith('Flashcards + Matching');
  });

  it('still seeds the duplicate with the source word list', () => {
    const deps = makeDeps(CURRICULUM);
    loadAssignmentIntoCreateForm(makeAssignment(), CLASS, true, deps);
    expect(deps.setSelectedWords).toHaveBeenCalledWith([1, 2, 3]);
  });
});

describe('loadAssignmentIntoCreateForm — custom-word classification', () => {
  it('does not file curriculum words as custom when the vocabulary is still cold', () => {
    const deps = makeDeps([]); // lazy chunk has not landed yet
    loadAssignmentIntoCreateForm(makeAssignment(), CLASS, false, deps);
    expect(deps.setCustomWords).toHaveBeenCalledWith([]);
    // …and it must not mislabel the whole set as the Custom tier.
    expect(deps.setSelectedLevel).not.toHaveBeenCalled();
  });

  it('keeps the real word ids selected even on a cold cache', () => {
    const deps = makeDeps([]);
    loadAssignmentIntoCreateForm(makeAssignment(), CLASS, false, deps);
    expect(deps.setSelectedWords).toHaveBeenCalledWith([1, 2, 3]);
  });

  it('detects genuine custom words by identity, cold cache or not', () => {
    const assignment = makeAssignment({
      wordIds: [1],
      words: [CURRICULUM[0], OCR_CUSTOM, LIBRARY_CUSTOM] as Word[],
    });
    for (const allWords of [[], CURRICULUM]) {
      const deps = makeDeps(allWords as Word[]);
      loadAssignmentIntoCreateForm(assignment, CLASS, false, deps);
      expect(deps.setCustomWords).toHaveBeenCalledWith([OCR_CUSTOM, LIBRARY_CUSTOM]);
    }
  });

  it('still preserves a stale curriculum id as a custom word once the corpus is loaded', () => {
    const stale = { id: 999, english: 'retired', hebrew: '—', arabic: '—', level: 'Set 1' } as unknown as Word;
    const deps = makeDeps(CURRICULUM);
    loadAssignmentIntoCreateForm(
      makeAssignment({ wordIds: [1, 999], words: [CURRICULUM[0], stale] as Word[] }),
      CLASS,
      false,
      deps,
    );
    expect(deps.setCustomWords).toHaveBeenCalledWith([stale]);
  });

  it('picks the Set 1 tier from the loaded corpus', () => {
    const deps = makeDeps(CURRICULUM);
    loadAssignmentIntoCreateForm(makeAssignment(), CLASS, false, deps);
    expect(deps.setSelectedLevel).toHaveBeenCalledWith('Set 1');
  });
});
