/**
 * NiqqudModeView — first VocaHebrew native-track game.
 *
 * Shows the lemma stripped of niqqud (e.g. כלב), then asks the
 * student to pick the correct vocalization out of 4 niqqud-marked
 * options.  Wrong options are generated by swapping one or two
 * niqqud marks in the correct form — they're pronounceable,
 * plausible, but wrong.  This is the same "minimal-pair" pattern
 * the founder uses on a whiteboard in 5th grade Hebrew classes.
 *
 * Audio: uses Web Speech API with a Hebrew voice when available, so
 * the student hears the correct vocalization the moment they answer.
 * No external audio files needed for the MVP — once the Hebrew TTS
 * pipeline ships (Google Cloud, mirrors scripts/generate-audio.ts),
 * this component will preload <audio> elements instead.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Volume2, ArrowLeft } from "lucide-react";
import {
  HEBREW_LEMMAS,
  HEBREW_LEMMAS_BY_GRADE,
} from "../data/vocabulary-hebrew";
import { stripNiqqud, type HebrewLemma } from "../data/types-hebrew";

// ─── Distractor generation ────────────────────────────────────────
//
// Pool of common Hebrew niqqud marks we swap between.  Excludes shin/
// sin dots and dagesh — those carry orthographic information that
// would change the consonant rather than the vowel, and a wrong
// dagesh produces something that doesn't read as Hebrew at all.
const VOWEL_NIQQUD = [
  "ְ", // sheva
  "ִ", // hiriq
  "ֵ", // tsere
  "ֶ", // segol
  "ַ", // patach
  "ָ", // qamatz
  "ֹ", // cholam
  "ֻ", // qubuts
] as const;

const isVowelNiqqud = (ch: string): boolean =>
  (VOWEL_NIQQUD as readonly string[]).includes(ch);

/** Generate `count` distractors by swapping 1 or 2 niqqud marks in
 *  the correct vocalization to plausibly-wrong vowels.  Falls back
 *  to fewer distractors if the lemma doesn't have enough vowel
 *  positions to mutate (rare in normative Hebrew). */
function makeDistractors(correct: string, count: number): string[] {
  const chars = Array.from(correct);
  const vowelPositions: number[] = [];
  chars.forEach((ch, i) => {
    if (isVowelNiqqud(ch)) vowelPositions.push(i);
  });
  if (vowelPositions.length === 0) return [];

  const out = new Set<string>();
  let safety = 0;
  while (out.size < count && safety < count * 10) {
    safety++;
    const pos = vowelPositions[Math.floor(Math.random() * vowelPositions.length)];
    const current = chars[pos];
    const swap = VOWEL_NIQQUD[Math.floor(Math.random() * VOWEL_NIQQUD.length)];
    if (swap === current) continue;
    const candidate = [...chars];
    candidate[pos] = swap;
    const variant = candidate.join("");
    if (variant !== correct) out.add(variant);
  }
  return [...out];
}

/** Shuffle in-place; returns same array for chaining. */
function shuffle<T>(arr: T[]): T[] {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// ─── Audio (Web Speech API fallback) ──────────────────────────────
function speakHebrew(text: string) {
  try {
    const utter = new SpeechSynthesisUtterance(text);
    utter.lang = "he-IL";
    utter.rate = 0.85;
    const voices = window.speechSynthesis.getVoices();
    const heVoice = voices.find((v) => v.lang.startsWith("he"));
    if (heVoice) utter.voice = heVoice;
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(utter);
  } catch { /* speech synthesis unavailable; silent */ }
}

// ─── Round state ──────────────────────────────────────────────────
interface Round {
  lemma: HebrewLemma;
  options: string[];
  correctIndex: number;
}

function buildRound(lemma: HebrewLemma): Round {
  const distractors = makeDistractors(lemma.lemmaNiqqud, 3);
  // If we couldn't generate 3 unique distractors, pad with other
  // lemmas' niqqud forms that share the same consonant skeleton.
  // Edge case — vanishingly rare with the curated seed.
  while (distractors.length < 3) distractors.push(lemma.lemmaNiqqud + "ַ");
  const options = shuffle([lemma.lemmaNiqqud, ...distractors]);
  return {
    lemma,
    options,
    correctIndex: options.indexOf(lemma.lemmaNiqqud),
  };
}

const ROUNDS_PER_SESSION = 10;

interface NiqqudModeViewProps {
  /** Tap "back" — returns to the VocaHebrew dashboard. */
  onExit: () => void;
  /** Optional grade filter — when provided, only lemmas matching
   *  this band show up.  null/undefined = mix of all grades. */
  gradeBand?: HebrewLemma["gradeBand"] | null;
}

export default function NiqqudModeView({ onExit, gradeBand }: NiqqudModeViewProps) {
  const lemmaPool = useMemo(() => {
    const pool = gradeBand
      ? (HEBREW_LEMMAS_BY_GRADE[gradeBand] ?? [])
      : HEBREW_LEMMAS;
    return shuffle([...pool]).slice(0, ROUNDS_PER_SESSION);
  }, [gradeBand]);

  const [roundIdx, setRoundIdx] = useState(0);
  const [picked, setPicked] = useState<number | null>(null);
  const [score, setScore] = useState(0);
  const [done, setDone] = useState(false);
  const advanceTimer = useRef<number | null>(null);

  const round = useMemo<Round | null>(() => {
    if (roundIdx >= lemmaPool.length) return null;
    return buildRound(lemmaPool[roundIdx]);
  }, [lemmaPool, roundIdx]);

  // Cleanup timer on unmount.
  useEffect(() => () => {
    if (advanceTimer.current) window.clearTimeout(advanceTimer.current);
  }, []);

  function handlePick(i: number) {
    if (picked !== null || !round) return;
    setPicked(i);
    const correct = i === round.correctIndex;
    if (correct) {
      setScore((s) => s + 1);
      speakHebrew(round.lemma.lemmaNiqqud);
    } else {
      // Voice the correct answer so the student hears what they
      // missed — the whole point of the mode is anchoring sound to
      // niqqud, so audio on wrong answers is mandatory.
      speakHebrew(round.lemma.lemmaNiqqud);
    }
    advanceTimer.current = window.setTimeout(() => {
      setPicked(null);
      if (roundIdx + 1 >= lemmaPool.length) {
        setDone(true);
      } else {
        setRoundIdx((idx) => idx + 1);
      }
    }, correct ? 900 : 1800);
  }

  function restart() {
    setRoundIdx(0);
    setPicked(null);
    setScore(0);
    setDone(false);
  }

  if (lemmaPool.length === 0) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-900 text-white p-4">
        <p className="font-bold">No Hebrew lemmas available for this grade band.</p>
      </div>
    );
  }

  if (done) {
    const pct = Math.round((score / lemmaPool.length) * 100);
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-950 to-indigo-950 flex items-center justify-center p-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="max-w-md w-full rounded-3xl bg-gradient-to-br from-blue-500 to-indigo-600 p-8 text-white text-center shadow-lg shadow-indigo-500/20"
        >
          <div className="text-7xl mb-4 drop-shadow-lg">
            {pct >= 80 ? "🏆" : pct >= 50 ? "🎯" : "💪"}
          </div>
          <h2 className="text-3xl font-black mb-2">
            {pct}% — {score} / {lemmaPool.length}
          </h2>
          <p className="font-bold mb-6 text-white/85">
            {pct >= 80
              ? "כל הכבוד! ניקוד מצוין"
              : pct >= 50
              ? "יפה מאוד, ממשיכים להתאמן"
              : "אל תוותר — עוד סיבוב"}
          </p>
          <div className="flex gap-3 justify-center">
            <button
              type="button"
              onClick={restart}
              style={{ touchAction: "manipulation", WebkitTapHighlightColor: "transparent" }}
              className="px-5 py-3 rounded-xl bg-white text-indigo-700 font-black text-sm tracking-wide shadow-sm hover:bg-amber-100"
            >
              Play again
            </button>
            <button
              type="button"
              onClick={onExit}
              style={{ touchAction: "manipulation", WebkitTapHighlightColor: "transparent" }}
              className="px-5 py-3 rounded-xl bg-white/10 backdrop-blur-sm border border-white/30 font-black text-sm tracking-wide hover:bg-white/15"
            >
              Back to VocaHebrew
            </button>
          </div>
        </motion.div>
      </div>
    );
  }

  if (!round) return null;

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-950 to-indigo-950 p-4 sm:p-8">
      <div className="max-w-2xl mx-auto">
        <header className="flex items-center justify-between mb-6">
          <button
            type="button"
            onClick={onExit}
            style={{ touchAction: "manipulation", WebkitTapHighlightColor: "transparent" }}
            className="inline-flex items-center gap-2 px-3 py-2 rounded-full bg-white/10 backdrop-blur-md border border-white/20 text-white text-xs font-black tracking-widest uppercase hover:bg-white/15"
          >
            <ArrowLeft size={14} />
            Back
          </button>
          <div className="text-white font-black text-sm">
            {roundIdx + 1} / {lemmaPool.length}
          </div>
          <div className="text-amber-300 font-black text-sm">{score} ✓</div>
        </header>

        <motion.div
          key={round.lemma.id}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
          className="text-center mb-8 sm:mb-10"
        >
          <p className="text-blue-300 font-black text-[10px] tracking-[0.25em] uppercase mb-3">
            Choose the correct niqqud
          </p>
          <div className="text-6xl sm:text-8xl font-black text-white drop-shadow-xl mb-4 leading-none" lang="he" dir="rtl">
            {stripNiqqud(round.lemma.lemmaNiqqud)}
          </div>
          <p className="text-white/70 font-bold text-sm sm:text-base" lang="he" dir="rtl">
            {round.lemma.definitionHe}
          </p>
          <p className="text-white/50 font-bold text-xs sm:text-sm mt-1">
            {round.lemma.translationEn} · {round.lemma.translationAr}
          </p>
        </motion.div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
          {round.options.map((opt, i) => {
            const isPicked = picked === i;
            const isCorrect = round.correctIndex === i;
            const showResult = picked !== null;
            const baseClass =
              "relative rounded-2xl p-5 sm:p-6 text-2xl sm:text-3xl font-black text-white shadow-lg overflow-hidden transition-all";
            let bgClass = "bg-gradient-to-br from-indigo-600 to-violet-700 hover:from-indigo-500 hover:to-violet-600 shadow-indigo-500/20";
            if (showResult) {
              if (isCorrect) {
                bgClass = "bg-gradient-to-br from-emerald-500 to-teal-600 shadow-emerald-500/30 ring-2 ring-emerald-300";
              } else if (isPicked) {
                bgClass = "bg-gradient-to-br from-rose-500 to-red-700 shadow-rose-500/30 ring-2 ring-rose-300";
              } else {
                bgClass = "bg-gradient-to-br from-slate-700 to-slate-800 opacity-60";
              }
            }
            return (
              <motion.button
                key={i}
                type="button"
                onClick={() => handlePick(i)}
                disabled={picked !== null}
                whileHover={picked === null ? { scale: 1.03, y: -2 } : undefined}
                whileTap={picked === null ? { scale: 0.97 } : undefined}
                style={{ touchAction: "manipulation", WebkitTapHighlightColor: "transparent" }}
                className={`${baseClass} ${bgClass}`}
                lang="he"
                dir="rtl"
              >
                <div className="absolute inset-0 bg-gradient-to-b from-white/15 to-transparent pointer-events-none" />
                <span className="relative z-10">{opt}</span>
              </motion.button>
            );
          })}
        </div>

        <AnimatePresence>
          {picked !== null && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              className="mt-6 text-center"
            >
              <button
                type="button"
                onClick={() => speakHebrew(round.lemma.lemmaNiqqud)}
                style={{ touchAction: "manipulation", WebkitTapHighlightColor: "transparent" }}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 backdrop-blur-md border border-white/20 text-white text-xs font-black tracking-widest uppercase hover:bg-white/15"
              >
                <Volume2 size={14} />
                Hear it again
              </button>
              <p className="mt-3 text-white/70 font-bold text-sm" lang="he" dir="rtl">
                {round.lemma.exampleHe}
              </p>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
