import { type ReactNode, useRef, useEffect, useState } from "react";
import { motion } from "motion/react";
import { AlertTriangle, ArrowLeft, KeyRound } from "lucide-react";
import StudentPinLoginCard from "../components/StudentPinLoginCard";
import type { View } from "../core/views";
import { useLanguage, languageNames, ALL_LANGUAGES, type Language } from "../hooks/useLanguage";
import { studentLoginT } from "../locales/student/student-login";
import { Globe } from "lucide-react";

interface StudentAccountLoginViewProps {
  setView: React.Dispatch<React.SetStateAction<View>>;
  /** Error banner text owned by App.tsx — typically the OAuth-reject
   *  notice routed here by useAuthRestore when a stale OAuth student
   *  session is restored, or any auth-restore failure that surfaces
   *  on this screen.  PIN flow has its own inline errors. */
  error: string | null;

  // Class code the student is joining (or returning to).
  studentLoginClassCode: string;
  setStudentLoginClassCode: (v: string) => void;

  // Global cookie banner passthrough
  cookieBannerOverlay: ReactNode;
}

// Extract a class code from whatever the student pasted. Handles:
//   * raw code:        "ABC12345"              -> "ABC12345"
//   * lowercase:       "abc12345"              -> "ABC12345"
//   * full URL:        "https://vocaband.com/?class=ABC12345" -> "ABC12345"
//   * URL shorthand:   "vocaband.com/?class=ABC12345"         -> "ABC12345"
//   * quoted + spaced: iOS sometimes wraps shared links in quotes.
//
// Teacher-shared links via WhatsApp / email / the classroom poster all
// route through here, so the student never has to manually copy just
// the code portion.
function normalizeClassCode(raw: string): string {
  if (!raw) return '';
  let s = raw.trim().replace(/^["'`]+|["'`]+$/g, '');
  const classMatch = s.match(/[?&]class=([A-Za-z0-9]+)/);
  if (classMatch) return classMatch[1].toUpperCase();
  return s.replace(/[^A-Za-z0-9]/g, '').toUpperCase();
}

// Class codes generated by handleCreateClass in App.tsx are 8 chars long.
const CODE_LENGTH = 8;

export default function StudentAccountLoginView({
  setView,
  error,
  studentLoginClassCode,
  setStudentLoginClassCode,
  cookieBannerOverlay,
}: StudentAccountLoginViewProps) {
  const codeInputRef = useRef<HTMLInputElement | null>(null);

  // Per-student teacher invite link prefill.  The teacher's "Share link"
  // button in ClassRosterModal generates URLs like:
  //   https://vocaband.com/student?class=ABC12345&s=<student_profile_id>
  // When the student opens that URL we forward `s=<uuid>` to
  // StudentPinLoginCard so it can auto-select the row and skip the
  // pick-your-name step.  Captured once on mount — subsequent picks /
  // back-taps are user-driven.
  const [prefilledStudentId] = useState<string | null>(() => {
    try {
      const params = new URLSearchParams(window.location.search);
      const raw = params.get('s');
      if (!raw) return null;
      // student_profiles.id is a UUID — accept the typical
      // 8-4-4-4-12 hex form (case-insensitive).  Anything else gets
      // dropped so a malformed param can't blow up the picker.
      if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(raw)) {
        return null;
      }
      return raw.toLowerCase();
    } catch { return null; }
  });

  // Auto-focus the (hidden) code input on mount.  On mobile this cues
  // the soft keyboard; on desktop, first keystroke lands in the right
  // place without the student hunting for a field.
  useEffect(() => {
    codeInputRef.current?.focus();
  }, []);

  // QR-code / teacher-shared-link pre-fill.
  //
  // The classroom poster's QR encodes a URL like:
  //   https://www.vocaband.com/?class=ABC12345&ref=teacher-ABC12345
  // Without this effect, a student scanning the QR landed on the login
  // form with an empty class-code field and had to type the 8 chars
  // manually — a friction point that defeats the purpose of the QR.
  //
  // On mount, read `?class=` from the current URL. If present, pre-fill
  // the code input so the student's only remaining task is the Google
  // sign-in.
  useEffect(() => {
    if (studentLoginClassCode) return; // Already filled — don't clobber.
    try {
      const params = new URLSearchParams(window.location.search);
      const raw = params.get('class');
      if (!raw) return;
      const normalized = normalizeClassCode(raw).slice(0, 20);
      if (normalized.length >= 3) {
        setStudentLoginClassCode(normalized);
      }
    } catch { /* URLSearchParams unavailable — noop */ }
    // Only runs once on mount; subsequent code typing is user-driven.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // QR-code / teacher-shared-link pre-fill.
  //
  // The classroom poster's QR encodes a URL like:
  //   https://www.vocaband.com/?class=ABC12345&ref=teacher-ABC12345
  // Without this effect, a student scanning the QR landed on the login
  // form with an empty class-code field and had to type the 8 chars
  // manually — a friction point that defeats the purpose of the QR.
  //
  // On mount, read `?class=` from the current URL.  If present and
  // the code field is still empty, pre-fill it + trigger the same
  // "Is that you?" roster load the student would otherwise get after
  // typing.  Only runs once per mount.
  useEffect(() => {
    if (studentLoginClassCode) return; // Already filled — don't clobber.
    try {
      const params = new URLSearchParams(window.location.search);
      const raw = params.get('class');
      if (!raw) return;
      const normalized = normalizeClassCode(raw).slice(0, 20);
      if (normalized.length >= 3) {
        setStudentLoginClassCode(normalized);
        // (loadStudentsInClass removed — the student picker now
        // fetches lazily on focus; the URL-param flow only seeds
        // the class-code input.)
      }
    } catch { /* URLSearchParams unavailable — noop */ }
    // Only runs once on mount; subsequent code typing is user-driven.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleCodeChange = (raw: string) => {
    const normalized = normalizeClassCode(raw).slice(0, 20);
    setStudentLoginClassCode(normalized);
  };

  // Character-box UI: eight slots that the student fills as they type.
  // Filled slots glow white (with soft indigo shadow); the next slot to
  // type in gets a ring so the caret position is obvious. Tapping any
  // slot focuses the underlying hidden input.
  const renderCodeBoxes = () => {
    const chars = studentLoginClassCode.split('').slice(0, CODE_LENGTH);
    const caret = Math.min(chars.length, CODE_LENGTH - 1);
    return (
      <div className="flex items-center justify-center gap-1.5 sm:gap-2">
        {Array.from({ length: CODE_LENGTH }).map((_, i) => {
          const ch = chars[i] ?? '';
          const isCaret = i === caret && ch === '';
          return (
            <button
              key={i}
              type="button"
              onClick={() => codeInputRef.current?.focus()}
              className={[
                'w-9 h-11 sm:w-11 sm:h-14 rounded-lg flex items-center justify-center text-xl sm:text-2xl font-black transition-all',
                ch
                  ? 'bg-white text-stone-900 shadow-lg shadow-indigo-500/30'
                  : 'bg-white/20 backdrop-blur-sm text-white/40',
                isCaret ? 'ring-2 ring-white/80' : '',
              ].join(' ')}
              tabIndex={-1}
              aria-hidden
            >
              {ch}
            </button>
          );
        })}
      </div>
    );
  };

  const hasEnoughCode = studentLoginClassCode.trim().length >= 3;
  const { language, setLanguage, isRTL } = useLanguage();
  const t = studentLoginT[language];
  const [langOpen, setLangOpen] = useState(false);
  const langs: Language[] = ALL_LANGUAGES;
  // Single login path: class code + roster-issued PIN.  Google /
  // Microsoft OAuth and email-OTP were removed in the 2026-05-18
  // privacy review (see PR #787 and PRIVACY_CHECKLIST §3) to align
  // with the privacy policy's claim that students never share a real
  // email address.  Teacher OAuth is unaffected — that flow lives in
  // TeacherLoginCard, not here.

  return (
    <>
      <div className="h-screen overflow-hidden bg-gradient-to-br from-indigo-900 via-violet-900 to-fuchsia-900 relative">
        {/* Soft decorative glow */}
        <div className="pointer-events-none absolute -top-24 -right-24 w-96 h-96 rounded-full bg-fuchsia-500/20 blur-3xl" aria-hidden />
        <div className="pointer-events-none absolute -bottom-24 -left-24 w-96 h-96 rounded-full bg-indigo-500/20 blur-3xl" aria-hidden />

        <div className="relative z-10 h-screen flex flex-col overflow-hidden">
            <header className="flex items-center justify-between px-4 sm:px-6 py-4">
              <button
                onClick={() => {
                  setView("public-landing");
                  setStudentLoginClassCode("");
                }}
                type="button"
                className="flex items-center gap-2 text-white/80 hover:text-white transition-colors font-bold text-sm px-3 py-2 rounded-full bg-white/10 backdrop-blur-sm"
              >
                <ArrowLeft size={16} className={isRTL ? 'rotate-180' : ''} />
                {t.back}
              </button>
              <div className="flex items-center gap-3">
                <span className="text-white/60 text-xs font-black uppercase tracking-[0.3em] hidden sm:inline">
                  {t.student}
                </span>
                {/* Language picker — students often need to change the
                    UI language before they can read the rest of the
                    login screen.  Surfacing it in the header (instead
                    of hiding it on the legal pages) makes the
                    EN/HE/AR translations from src/locales/student/*
                    actually reachable.  Once selected, useLanguage
                    persists the choice via localStorage so the
                    dashboard, games, and shop all inherit it. */}
                <div className="relative">
                  <button
                    onClick={() => setLangOpen(o => !o)}
                    type="button"
                    aria-label={language === 'he' ? 'החלף שפה' : language === 'ar' ? 'تغيير اللغة' : 'Change language'}
                    aria-expanded={langOpen}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white/10 backdrop-blur-sm text-white text-xs font-bold hover:bg-white/20 transition-colors"
                    style={{ touchAction: 'manipulation' }}
                  >
                    <Globe size={14} />
                    <span>{languageNames[language]}</span>
                  </button>
                  {langOpen && (
                    <>
                      <div className="fixed inset-0 z-40" onClick={() => setLangOpen(false)} />
                      <div className="absolute top-full mt-2 end-0 z-50 bg-white rounded-lg shadow-xl border border-stone-200 overflow-hidden min-w-[160px]">
                        {langs.map(lng => (
                          <button
                            key={lng}
                            onClick={() => { setLanguage(lng); setLangOpen(false); }}
                            type="button"
                            style={{ touchAction: 'manipulation' }}
                            className={`w-full flex items-center gap-2 px-3 py-2 text-sm font-medium hover:bg-stone-50 transition-colors ${
                              language === lng ? 'bg-indigo-50 text-indigo-700' : 'text-stone-700'
                            }`}
                          >
                            <Globe size={14} aria-hidden />
                            <span>{languageNames[lng]}</span>
                          </button>
                        ))}
                      </div>
                    </>
                  )}
                </div>
              </div>
            </header>

            <main id="main-content" className="flex-1 min-h-0 flex items-center justify-center px-4 py-2 sm:py-4">
              <motion.div
                initial={{ opacity: 0, y: 24 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ type: 'spring', stiffness: 120, damping: 18 }}
                className="w-full max-w-xl"
              >
                {/* Hero — compact so the whole login fits in one screen
                    without scrolling.  Icon shrinks on phones; the title
                    block tightens its leading; the wrapper margin
                    collapses on shorter viewports. */}
                <div className="flex items-center gap-3 sm:gap-5 mb-4 sm:mb-6">
                  <motion.img
                    src="/icon.svg"
                    alt="Vocaband"
                    className="w-14 h-14 sm:w-20 sm:h-20 shrink-0 drop-shadow-[0_8px_24px_rgba(236,72,153,0.35)]"
                    initial={{ rotate: -15, scale: 0.7 }}
                    animate={{ rotate: [0, -3, 3, 0], scale: 1 }}
                    transition={{
                      rotate: { duration: 5, repeat: Infinity, ease: "easeInOut" },
                      scale:  { type: 'spring', stiffness: 180, damping: 12 },
                    }}
                  />
                  <div>
                    <h1 className="text-2xl sm:text-4xl font-black text-white leading-[0.95] tracking-tight">
                      {t.heroLine1}<br />{t.heroLine2}
                    </h1>
                    <p className="mt-1 text-sm sm:text-base font-bold text-white/80">
                      {t.heroSubtitle}
                    </p>
                  </div>
                </div>

                <div className="bg-white/95 backdrop-blur-sm rounded-2xl shadow-2xl p-4 sm:p-6">
                  {/* Class-code entry */}
                  <div className="mb-5">
                    <label
                      htmlFor="student-class-code-input"
                      className="block text-[11px] font-black uppercase tracking-[0.2em] text-stone-500 text-center mb-3"
                    >
                      {t.classCodeLabel}
                    </label>

                    <div className="bg-gradient-to-br from-indigo-600 via-violet-600 to-fuchsia-600 rounded-xl p-4 shadow-inner">
                      {renderCodeBoxes()}
                    </div>
                    <input
                      ref={codeInputRef}
                      id="student-class-code-input"
                      name="classCode"
                      type="text"
                      autoComplete="off"
                      autoCapitalize="characters"
                      inputMode="text"
                      spellCheck={false}
                      value={studentLoginClassCode}
                      onChange={(e) => handleCodeChange(e.target.value)}
                      onPaste={(e) => {
                        // Intercept paste so teacher-shared URLs like
                        //   https://vocaband.com/?class=ABC12345
                        // get reduced to just the code automatically.
                        const pasted = e.clipboardData.getData('text');
                        if (pasted) {
                          e.preventDefault();
                          handleCodeChange(pasted);
                        }
                      }}
                      maxLength={20}
                      aria-label={t.classCodeAria}
                      aria-describedby={error ? "student-login-error" : "class-code-hint"}
                      className="sr-only"
                    />
                    <p id="class-code-hint" className="text-xs text-stone-500 text-center mt-3">
                      {t.classCodeHint}
                    </p>

                    {error && (
                      <motion.div
                        id="student-login-error"
                        initial={{ opacity: 0, y: -10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="mt-3 bg-rose-50 border border-rose-200 text-rose-800 px-4 py-3 rounded-lg text-sm font-bold flex items-start gap-2"
                        role="alert"
                      >
                        <AlertTriangle size={18} className="mt-0.5 flex-shrink-0" aria-hidden="true" />
                        <span>{error}</span>
                      </motion.div>
                    )}
                  </div>

                  {/* PIN-only auth.  The previous toggle to Google /
                      Microsoft OAuth + email-OTP was removed in the
                      2026-05-18 privacy review to align the student
                      experience with the privacy policy's claim that
                      students share no real email address. */}
                  {hasEnoughCode ? (
                    <StudentPinLoginCard
                      classCode={studentLoginClassCode.trim().toUpperCase()}
                      prefilledStudentId={prefilledStudentId}
                      onSuccess={() => {
                        // Supabase session is live; App.tsx's
                        // onAuthStateChange listener will hydrate the
                        // AppUser from public.users on its own.
                      }}
                    />
                  ) : (
                    <div className="text-center py-4">
                      <KeyRound size={22} className="text-stone-400 mx-auto mb-2" />
                      <p className="text-sm font-bold text-stone-600">Enter your class code above</p>
                      <p className="text-xs text-stone-500 mt-1">Then pick your name and type your PIN.</p>
                    </div>
                  )}

                  <p className="mt-4 text-xs text-stone-500 text-center leading-relaxed">
                    {hasEnoughCode ? t.signedInBefore : t.firstTime}
                  </p>
                </div>

                {/* Feature chips — subtle reminder of what students get */}
                <div className="mt-3 sm:mt-4 flex flex-wrap justify-center gap-2">
                  {t.features.map(f => (
                    <span
                      key={f.text}
                      className="px-3 py-1.5 bg-white/10 backdrop-blur-sm rounded-full text-xs font-bold text-white/90 border border-white/10"
                    >
                      <span className="me-1">{f.emoji}</span>
                      {f.text}
                    </span>
                  ))}
                </div>
              </motion.div>
            </main>

            <footer className="py-2 sm:py-3 text-center text-white/40 text-xs font-bold">
              vocaband.com
            </footer>
          </div>
        {cookieBannerOverlay}
      </div>
    </>
  );
}
