import { type ReactNode, useRef, useEffect, useState } from "react";
import { motion } from "motion/react";
import { AlertTriangle, ArrowLeft, KeyRound } from "lucide-react";
import OAuthCallback from "../components/OAuthCallback";
import OAuthClassCode from "../components/OAuthClassCode";
import OAuthButton from "../components/OAuthButton";
import StudentEmailOtpCard from "../components/StudentEmailOtpCard";
import StudentPinLoginCard from "../components/StudentPinLoginCard";
import type { View } from "../core/views";
import { writeIntendedClassCode } from "../utils/oauthIntent";
import { useLanguage, languageNames, type Language } from "../hooks/useLanguage";
import { studentLoginT } from "../locales/student/student-login";
import { Globe } from "lucide-react";

interface StudentAccountLoginViewProps {
  setView: React.Dispatch<React.SetStateAction<View>>;
  error: string | null;
  setError: (err: string | null) => void;

  // Class code the student is joining (or returning to).
  studentLoginClassCode: string;
  setStudentLoginClassCode: (v: string) => void;

  // OAuth flow state
  isOAuthCallback: boolean;
  setIsOAuthCallback: (v: boolean) => void;
  showOAuthClassCode: boolean;
  setShowOAuthClassCode: (v: boolean) => void;
  oauthEmail: string | null;
  setOauthEmail: (v: string | null) => void;
  oauthAuthUid: string | null;
  setOauthAuthUid: (v: string | null) => void;

  // Handlers
  handleOAuthTeacherDetected: (email: string) => Promise<void>;
  handleOAuthStudentDetected: (email: string) => Promise<void>;
  handleOAuthNewUser: (email: string, authUid: string) => void;

  // Global cookie banner passthrough
  cookieBannerOverlay: ReactNode;
}

// Extract a class code from whatever the student pasted. Handles:
//   * raw code:        "ABC12345"              -> "ABC12345"
//   * lowercase:       "abc12345"              -> "ABC12345"
//   * full URL:        "https://vocaband.com/?class=ABC12345" -> "ABC12345"
//   * URL shorthand:   "vocaband.com/?class=ABC12345"         -> "ABC12345"
//   * quoted + spaced: iOS sometimes wraps shared links in quotes.
//
// Teacher-shared links via WhatsApp / email / the classroom poster all
// route through here, so the student never has to manually copy just
// the code portion.
function normalizeClassCode(raw: string): string {
  if (!raw) return '';
  let s = raw.trim().replace(/^["'`]+|["'`]+$/g, '');
  const classMatch = s.match(/[?&]class=([A-Za-z0-9]+)/);
  if (classMatch) return classMatch[1].toUpperCase();
  return s.replace(/[^A-Za-z0-9]/g, '').toUpperCase();
}

// Class codes generated by handleCreateClass in App.tsx are 8 chars long.
const CODE_LENGTH = 8;

export default function StudentAccountLoginView({
  setView,
  error,
  setError,
  studentLoginClassCode,
  setStudentLoginClassCode,
  isOAuthCallback,
  setIsOAuthCallback,
  showOAuthClassCode,
  setShowOAuthClassCode,
  oauthEmail,
  setOauthEmail,
  oauthAuthUid,
  setOauthAuthUid,
  handleOAuthTeacherDetected,
  handleOAuthStudentDetected,
  handleOAuthNewUser,
  cookieBannerOverlay,
}: StudentAccountLoginViewProps) {
  const codeInputRef = useRef<HTMLInputElement | null>(null);

  // Auto-focus the (hidden) code input when the primary screen is up.
  // On mobile this cues the soft keyboard; on desktop, first keystroke
  // lands in the right place without the student hunting for a field.
  useEffect(() => {
    if (!isOAuthCallback && !showOAuthClassCode) {
      codeInputRef.current?.focus();
    }
  }, [isOAuthCallback, showOAuthClassCode]);

  // QR-code / teacher-shared-link pre-fill.
  //
  // The classroom poster's QR encodes a URL like:
  //   https://www.vocaband.com/?class=ABC12345&ref=teacher-ABC12345
  // Without this effect, a student scanning the QR landed on the login
  // form with an empty class-code field and had to type the 8 chars
  // manually — a friction point that defeats the purpose of the QR.
  //
  // On mount, read `?class=` from the current URL. If present, pre-fill
  // the code input so the student's only remaining task is the Google
  // sign-in.
  useEffect(() => {
    if (studentLoginClassCode) return; // Already filled — don't clobber.
    try {
      const params = new URLSearchParams(window.location.search);
      const raw = params.get('class');
      if (!raw) return;
      const normalized = normalizeClassCode(raw).slice(0, 20);
      if (normalized.length >= 3) {
        setStudentLoginClassCode(normalized);
      }
    } catch { /* URLSearchParams unavailable — noop */ }
    // Only runs once on mount; subsequent code typing is user-driven.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // QR-code / teacher-shared-link pre-fill.
  //
  // The classroom poster's QR encodes a URL like:
  //   https://www.vocaband.com/?class=ABC12345&ref=teacher-ABC12345
  // Without this effect, a student scanning the QR landed on the login
  // form with an empty class-code field and had to type the 8 chars
  // manually — a friction point that defeats the purpose of the QR.
  //
  // On mount, read `?class=` from the current URL.  If present and
  // the code field is still empty, pre-fill it + trigger the same
  // "Is that you?" roster load the student would otherwise get after
  // typing.  Only runs once per mount.
  useEffect(() => {
    if (studentLoginClassCode) return; // Already filled — don't clobber.
    try {
      const params = new URLSearchParams(window.location.search);
      const raw = params.get('class');
      if (!raw) return;
      const normalized = normalizeClassCode(raw).slice(0, 20);
      if (normalized.length >= 3) {
        setStudentLoginClassCode(normalized);
        // (loadStudentsInClass removed — the student picker now
        // fetches lazily on focus; the URL-param flow only seeds
        // the class-code input.)
      }
    } catch { /* URLSearchParams unavailable — noop */ }
    // Only runs once on mount; subsequent code typing is user-driven.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleCodeChange = (raw: string) => {
    const normalized = normalizeClassCode(raw).slice(0, 20);
    setStudentLoginClassCode(normalized);
  };

  // Character-box UI: eight slots that the student fills as they type.
  // Filled slots glow white (with soft indigo shadow); the next slot to
  // type in gets a ring so the caret position is obvious. Tapping any
  // slot focuses the underlying hidden input.
  const renderCodeBoxes = () => {
    const chars = studentLoginClassCode.split('').slice(0, CODE_LENGTH);
    const caret = Math.min(chars.length, CODE_LENGTH - 1);
    return (
      <div className="flex items-center justify-center gap-1.5 sm:gap-2">
        {Array.from({ length: CODE_LENGTH }).map((_, i) => {
          const ch = chars[i] ?? '';
          const isCaret = i === caret && ch === '';
          return (
            <button
              key={i}
              type="button"
              onClick={() => codeInputRef.current?.focus()}
              className={[
                'w-9 h-11 sm:w-11 sm:h-14 rounded-xl flex items-center justify-center text-xl sm:text-2xl font-black transition-all',
                ch
                  ? 'bg-white text-stone-900 shadow-lg shadow-indigo-500/30'
                  : 'bg-white/20 backdrop-blur-sm text-white/40',
                isCaret ? 'ring-2 ring-white/80' : '',
              ].join(' ')}
              tabIndex={-1}
              aria-hidden
            >
              {ch}
            </button>
          );
        })}
      </div>
    );
  };

  const hasEnoughCode = studentLoginClassCode.trim().length >= 3;
  const { language, setLanguage } = useLanguage();
  const t = studentLoginT[language];
  const [langOpen, setLangOpen] = useState(false);
  const langs: Language[] = ["en", "he", "ar"];
  // Three login paths, in order of preference for the Israeli market:
  //   - "pin"   : teacher pre-creates a roster row + PIN; the student
  //               picks their name and types the PIN.  Default — no
  //               Google account needed (matches MoE-issued devices).
  //   - "oauth" : Google + Microsoft + a link to email-OTP.  Backup
  //               for students who aren't on the roster yet or who
  //               attend a school where OAuth is preferred.
  //   - "otp"   : email magic-code.  Reached via a button inside the
  //               OAuth panel; identity ends up in the same session
  //               either way.
  const [authMode, setAuthMode] = useState<"pin" | "oauth" | "otp">("pin");

  return (
    <>
      <div className="min-h-screen bg-gradient-to-br from-indigo-900 via-violet-900 to-fuchsia-900 relative overflow-hidden">
        {/* Soft decorative glow */}
        <div className="pointer-events-none absolute -top-24 -right-24 w-96 h-96 rounded-full bg-fuchsia-500/20 blur-3xl" aria-hidden />
        <div className="pointer-events-none absolute -bottom-24 -left-24 w-96 h-96 rounded-full bg-indigo-500/20 blur-3xl" aria-hidden />

        {/* OAuth callback — shown when Google redirected us back while the
            login view was still mounted. */}
        {isOAuthCallback && (
          <OAuthCallback
            onTeacherDetected={handleOAuthTeacherDetected}
            onStudentDetected={handleOAuthStudentDetected}
            onNewUser={handleOAuthNewUser}
          />
        )}

        {/* OAuth new-user class-code screen — shown when Google succeeded
            but there's no student profile yet for this email. */}
        {showOAuthClassCode && oauthEmail && oauthAuthUid && (
          <div className="relative z-10 min-h-screen flex items-center justify-center px-4 py-6">
            <div className="bg-white/95 backdrop-blur-sm rounded-3xl shadow-2xl w-full max-w-md">
              <OAuthClassCode
                email={oauthEmail}
                authUid={oauthAuthUid}
                onSuccess={() => {
                  setShowOAuthClassCode(false);
                  setOauthEmail(null);
                  setOauthAuthUid(null);
                }}
                onError={(msg) => {
                  setError(msg);
                  // Stay on the class-code screen so the student can fix + retry.
                }}
              />
            </div>
          </div>
        )}

        {/* Primary login screen — class code + Google. Google is the only
            login path: one path students can always trust, works on every
            device, no per-browser session state to lose. */}
        {!isOAuthCallback && !showOAuthClassCode && (
          <div className="relative z-10 min-h-screen flex flex-col">
            <header className="flex items-center justify-between px-4 sm:px-6 py-4">
              <button
                onClick={() => {
                  setView("public-landing");
                  setStudentLoginClassCode("");
                }}
                type="button"
                className="flex items-center gap-2 text-white/80 hover:text-white transition-colors font-bold text-sm px-3 py-2 rounded-full bg-white/10 backdrop-blur-sm"
              >
                <ArrowLeft size={16} />
                {t.back}
              </button>
              <div className="flex items-center gap-3">
                <span className="text-white/60 text-xs font-black uppercase tracking-[0.3em] hidden sm:inline">
                  {t.student}
                </span>
                {/* Language picker — students often need to change the
                    UI language before they can read the rest of the
                    login screen.  Surfacing it in the header (instead
                    of hiding it on the legal pages) makes the
                    EN/HE/AR translations from src/locales/student/*
                    actually reachable.  Once selected, useLanguage
                    persists the choice via localStorage so the
                    dashboard, games, and shop all inherit it. */}
                <div className="relative">
                  <button
                    onClick={() => setLangOpen(o => !o)}
                    type="button"
                    aria-label={language === 'he' ? 'החלף שפה' : language === 'ar' ? 'تغيير اللغة' : 'Change language'}
                    aria-expanded={langOpen}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white/10 backdrop-blur-sm text-white text-xs font-bold hover:bg-white/20 transition-colors"
                    style={{ touchAction: 'manipulation' }}
                  >
                    <Globe size={14} />
                    <span>{languageNames[language]}</span>
                  </button>
                  {langOpen && (
                    <>
                      <div className="fixed inset-0 z-40" onClick={() => setLangOpen(false)} />
                      <div className="absolute top-full mt-2 right-0 z-50 bg-white rounded-xl shadow-xl border border-stone-200 overflow-hidden min-w-[160px]">
                        {langs.map(lng => (
                          <button
                            key={lng}
                            onClick={() => { setLanguage(lng); setLangOpen(false); }}
                            type="button"
                            style={{ touchAction: 'manipulation' }}
                            className={`w-full flex items-center gap-2 px-3 py-2 text-sm font-medium hover:bg-stone-50 transition-colors ${
                              language === lng ? 'bg-indigo-50 text-indigo-700' : 'text-stone-700'
                            }`}
                          >
                            <Globe size={14} aria-hidden />
                            <span>{languageNames[lng]}</span>
                          </button>
                        ))}
                      </div>
                    </>
                  )}
                </div>
              </div>
            </header>

            <main id="main-content" className="flex-1 flex items-center justify-center px-4 py-6 sm:py-10">
              <motion.div
                initial={{ opacity: 0, y: 24 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ type: 'spring', stiffness: 120, damping: 18 }}
                className="w-full max-w-xl"
              >
                {/* Hero */}
                <div className="flex items-center gap-4 sm:gap-6 mb-8 sm:mb-10">
                  <motion.img
                    src="/icon.svg"
                    alt="Vocaband"
                    className="w-20 h-20 sm:w-24 sm:h-24 shrink-0 drop-shadow-[0_8px_24px_rgba(236,72,153,0.35)]"
                    initial={{ rotate: -15, scale: 0.7 }}
                    animate={{ rotate: [0, -3, 3, 0], scale: 1 }}
                    transition={{
                      rotate: { duration: 5, repeat: Infinity, ease: "easeInOut" },
                      scale:  { type: 'spring', stiffness: 180, damping: 12 },
                    }}
                  />
                  <div>
                    <h1 className="text-3xl sm:text-5xl font-black text-white leading-[0.95] tracking-tight">
                      {t.heroLine1}<br />{t.heroLine2}
                    </h1>
                    <p className="mt-2 text-base sm:text-lg font-bold text-white/80">
                      {t.heroSubtitle}
                    </p>
                  </div>
                </div>

                <div className="bg-white/95 backdrop-blur-sm rounded-3xl shadow-2xl p-6 sm:p-8">
                  {/* Class-code entry */}
                  <div className="mb-5">
                    <label
                      htmlFor="student-class-code-input"
                      className="block text-[11px] font-black uppercase tracking-[0.2em] text-stone-500 text-center mb-3"
                    >
                      {t.classCodeLabel}
                    </label>

                    <div className="bg-gradient-to-br from-indigo-600 via-violet-600 to-fuchsia-600 rounded-2xl p-4 shadow-inner">
                      {renderCodeBoxes()}
                    </div>
                    <input
                      ref={codeInputRef}
                      id="student-class-code-input"
                      name="classCode"
                      type="text"
                      autoComplete="off"
                      autoCapitalize="characters"
                      inputMode="text"
                      spellCheck={false}
                      value={studentLoginClassCode}
                      onChange={(e) => handleCodeChange(e.target.value)}
                      onPaste={(e) => {
                        // Intercept paste so teacher-shared URLs like
                        //   https://vocaband.com/?class=ABC12345
                        // get reduced to just the code automatically.
                        const pasted = e.clipboardData.getData('text');
                        if (pasted) {
                          e.preventDefault();
                          handleCodeChange(pasted);
                        }
                      }}
                      maxLength={20}
                      aria-label={t.classCodeAria}
                      aria-describedby={error ? "student-login-error" : "class-code-hint"}
                      className="sr-only"
                    />
                    <p id="class-code-hint" className="text-xs text-stone-500 text-center mt-3">
                      {t.classCodeHint}
                    </p>

                    {error && (
                      <motion.div
                        id="student-login-error"
                        initial={{ opacity: 0, y: -10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="mt-3 bg-rose-50 border border-rose-200 text-rose-800 px-4 py-3 rounded-xl text-sm font-bold flex items-start gap-2"
                        role="alert"
                      >
                        <AlertTriangle size={18} className="mt-0.5 flex-shrink-0" aria-hidden="true" />
                        <span>{error}</span>
                      </motion.div>
                    )}
                  </div>

                  {/* Auth panel — picks one of three paths:
                      - "pin"  : teacher-issued PIN (primary; default)
                      - "oauth": Google + Microsoft
                      - "otp"  : email magic-code (reached from inside oauth)
                      The PIN path doesn't need a Google/Microsoft account,
                      which matches most Israeli classrooms and lets a
                      4th-grader join without parental email setup. */}
                  {authMode === "pin" ? (
                    hasEnoughCode ? (
                      <StudentPinLoginCard
                        classCode={studentLoginClassCode.trim().toUpperCase()}
                        onSuccess={() => {
                          // Supabase session is live; App.tsx's
                          // onAuthStateChange listener will hydrate the
                          // AppUser from public.users on its own.
                        }}
                        onUseDifferentMethod={() => setAuthMode("oauth")}
                      />
                    ) : (
                      <div className="text-center py-4">
                        <KeyRound size={22} className="text-stone-400 mx-auto mb-2" />
                        <p className="text-sm font-bold text-stone-600">Enter your class code above</p>
                        <p className="text-xs text-stone-500 mt-1">Then pick your name and type your PIN.</p>
                      </div>
                    )
                  ) : authMode === "otp" ? (
                    <StudentEmailOtpCard
                      classCode={studentLoginClassCode}
                      onVerified={() => setIsOAuthCallback(true)}
                      onUseGoogle={() => setAuthMode("oauth")}
                    />
                  ) : (
                    <>
                      <OAuthButton
                        onSuccess={() => {
                          setIsOAuthCallback(true);
                        }}
                        onError={(errorMessage) => {
                          setError(errorMessage);
                        }}
                        beforeSignIn={() => {
                          writeIntendedClassCode(studentLoginClassCode.trim().toUpperCase());
                        }}
                      />
                      <OAuthButton
                        provider="azure"
                        label={t.signInWithMicrosoft}
                        onSuccess={() => {
                          setIsOAuthCallback(true);
                        }}
                        onError={(errorMessage) => {
                          setError(errorMessage);
                        }}
                        beforeSignIn={() => {
                          writeIntendedClassCode(studentLoginClassCode.trim().toUpperCase());
                        }}
                      />
                      <button
                        type="button"
                        onClick={() => setAuthMode("otp")}
                        className="w-full mt-3 text-xs font-bold text-stone-500 hover:text-stone-900 inline-flex items-center justify-center gap-1.5 py-2 rounded-lg hover:bg-stone-100 transition-colors"
                        style={{ touchAction: 'manipulation', WebkitTapHighlightColor: 'transparent' as unknown as string }}
                      >
                        Or use email instead
                      </button>
                      <button
                        type="button"
                        onClick={() => setAuthMode("pin")}
                        className="w-full mt-1 text-xs font-bold text-indigo-600 hover:text-indigo-800 inline-flex items-center justify-center gap-1.5 py-2 rounded-lg hover:bg-indigo-50 transition-colors"
                        style={{ touchAction: 'manipulation', WebkitTapHighlightColor: 'transparent' as unknown as string }}
                      >
                        <KeyRound size={12} /> I have a PIN from my teacher
                      </button>
                    </>
                  )}

                  <p className="mt-4 text-xs text-stone-500 text-center leading-relaxed">
                    {hasEnoughCode ? t.signedInBefore : t.firstTime}
                  </p>
                </div>

                {/* Feature chips — subtle reminder of what students get */}
                <div className="mt-6 flex flex-wrap justify-center gap-2">
                  {t.features.map(f => (
                    <span
                      key={f.text}
                      className="px-3 py-1.5 bg-white/10 backdrop-blur-sm rounded-full text-xs font-bold text-white/90 border border-white/10"
                    >
                      <span className="mr-1">{f.emoji}</span>
                      {f.text}
                    </span>
                  ))}
                </div>
              </motion.div>
            </main>

            <footer className="py-5 text-center text-white/40 text-xs font-bold">
              vocaband.com
            </footer>
          </div>
        )}
        {cookieBannerOverlay}
      </div>
    </>
  );
}
