/**
 * The teacher-dashboard view branch — TeacherDashboardView + the
 * Voca-switcher button + ClassRosterModal — pulled out of App.tsx
 * so the 186-line JSX block doesn't crowd the orchestrator.
 *
 * Behaviour preserved exactly.  Closure deps from App's render scope
 * (state, setters, sibling-hook helpers) come in via TeacherDashboardContext
 * (App.tsx wraps this branch in a TeacherDashboardProvider).
 */
import { Suspense, type ReactNode } from 'react';
import { lazyWithRetry } from '../utils/lazyWithRetry';
import { LazyWrapper } from '../components/SuspenseWrapper';
// Lazy — both pull in motion/react and only mount when a roster modal is
// opened. Loading them eagerly put motion on the cold first-paint path.
const ClassRosterModal = lazyWithRetry(() => import('../components/ClassRosterModal'));
const RosterModalV2 = lazyWithRetry(() => import('../components/roster/v2/RosterModalV2'));
import SvgArrowLeftRight from '../components/svg/SvgArrowLeftRight';
import { logAudit } from '../utils/audit';
import {
  deleteAssignmentWithUndo,
  deleteAssignmentImmediate,
} from '../handlers/deleteAssignmentWithUndo';
import { saveClassEdit, renameClass, changeClassAvatar } from '../handlers/classEdits';
import {
  completeTeacherOnboarding,
  skipTeacherOnboarding,
} from '../handlers/teacherOnboarding';
import {
  startQuickPlayFromDashboard,
  startCategoryRaceFromDashboard,
  startAssignClassFlow,
  loadAssignmentIntoCreateForm,
  applySavedTask,
} from '../handlers/teacherDashboardActions';
import type { SavedTask } from '../hooks/useSavedTasks';
import { useTeacherDashboard, type TeacherDashboardSectionDeps } from './TeacherDashboardContext';

// Re-export so existing importers keep resolving the deps type from here.
export type { TeacherDashboardSectionDeps };

const TeacherDashboardView = lazyWithRetry(() => import('./TeacherDashboardView'));

export function TeacherDashboardSection(): ReactNode {
  const deps = useTeacherDashboard();
  const {
    user, activeVoca, showVocaSwitcher, setActiveVoca, setView, setUser,
    consentModal, exitConfirmModal, ocrCropModal,
    showOnboarding, setShowOnboarding,
    visibleClasses, visibleAssignments, pendingStudentsCount,
    copiedCode, setCopiedCode, openDropdownClassId, setOpenDropdownClassId,
    showCreateClassModal, setShowCreateClassModal,
    newClassName, setNewClassName, handleCreateClass,
    createdClassCode, createdClassName, setCreatedClassCode,
    deleteConfirmModal, setDeleteConfirmModal,
    setTeacherAssignments, setToasts, showToast, appToasts,
    rejectStudentModal, setRejectStudentModal, confirmRejectStudent,
    toasts, confirmDialog, setConfirmDialog,
    cleanupSessionData, setQuickPlayActiveSession, setQuickPlaySessionCode,
    fetchScores, fetchTeacherAssignments, loadPendingStudents,
    setActivityNavOrigin, setClassShowAssignment, setWorksheetAssignment,
    setSelectedClass, selectedClass, classes,
    setAssignmentStep, setSelectedWords, setAssignmentTitle,
    setAssignmentDeadline, setAssignmentModes, setAssignmentSentences,
    setEditingAssignment, handleDeleteClass,
    editingClass, setEditingClass, setClasses,
    allWords, set1Words, setCustomWords,
    setSentenceDifficulty, setSentencesAutoGenerated, setSelectedLevel,
    setRosterModalClass, rosterModalClass,
    savedTasks, setQuickPlaySelectedWords, setQuickPlayInitialModes,
  } = deps;

  // Voca switcher button — rendered inside TopAppBar's controls, sits
  // in the flex flow next to the language switcher (not floated).
  const vocaSwitcherButton = showVocaSwitcher ? (
    <button
      type="button"
      onClick={() => { setActiveVoca(null); setView('voca-picker'); }}
      style={{ touchAction: 'manipulation', WebkitTapHighlightColor: 'transparent' }}
      className="inline-flex items-center gap-1.5 px-3 py-2 rounded-full bg-indigo-600 text-white text-[10px] sm:text-xs font-black tracking-wider shadow-sm hover:bg-indigo-500 active:scale-95 transition"
      title={activeVoca === 'hebrew' ? 'החלף ל-Voca אחר' : 'Switch to another Voca'}
    >
      <SvgArrowLeftRight size={12} />
      <span className="hidden sm:inline">{activeVoca === 'hebrew' ? 'החלף Voca' : 'Switch Voca'}</span>
      <span className="sm:hidden">{activeVoca === 'hebrew' ? 'החלף' : 'Switch'}</span>
    </button>
  ) : null;

  // Deps bag shared by the dashboard's medium-sized inline handlers.
  const tdActionDeps = {
    allWords, set1Words,
    setEditingAssignment, setSelectedWords, setCustomWords,
    setAssignmentTitle, setAssignmentDeadline, setAssignmentModes,
    setAssignmentSentences, setSentenceDifficulty, setSentencesAutoGenerated,
    setSelectedLevel, setSelectedClass, setView,
  };

  return (
    <LazyWrapper loadingMessage="Loading dashboard...">
      <TeacherDashboardView
        user={user}
        setUser={setUser}
        subject={activeVoca ?? 'english'}
        headerExtra={vocaSwitcherButton}
        consentModal={consentModal}
        exitConfirmModal={exitConfirmModal}
        ocrCropModal={ocrCropModal}
        showOnboarding={showOnboarding}
        setShowOnboarding={setShowOnboarding}
        classes={visibleClasses}
        teacherAssignments={visibleAssignments}
        pendingStudentsCount={pendingStudentsCount}
        copiedCode={copiedCode}
        setCopiedCode={setCopiedCode}
        openDropdownClassId={openDropdownClassId}
        setOpenDropdownClassId={setOpenDropdownClassId}
        showCreateClassModal={showCreateClassModal}
        setShowCreateClassModal={setShowCreateClassModal}
        newClassName={newClassName}
        setNewClassName={setNewClassName}
        handleCreateClass={handleCreateClass}
        createdClassCode={createdClassCode}
        createdClassName={createdClassName}
        setCreatedClassCode={setCreatedClassCode}
        deleteConfirmModal={deleteConfirmModal}
        setDeleteConfirmModal={setDeleteConfirmModal}
        onConfirmDeleteAssignment={(deletedId, deletedTitle) =>
          deleteAssignmentWithUndo(deletedId, deletedTitle, {
            setTeacherAssignments, setDeleteConfirmModal, setToasts, showToast,
            failedDeleteMsg: appToasts.failedDeleteFromDb,
            restoredMsg: appToasts.assignmentRestored,
          })
        }
        rejectStudentModal={rejectStudentModal}
        setRejectStudentModal={setRejectStudentModal}
        confirmRejectStudent={confirmRejectStudent}
        toasts={toasts}
        confirmDialog={confirmDialog}
        setConfirmDialog={setConfirmDialog}
        onQuickPlayClick={() => startQuickPlayFromDashboard({
          cleanupSessionData, setQuickPlayActiveSession, setQuickPlaySessionCode, setView,
        })}
        onCategoryRaceClick={() => { void startCategoryRaceFromDashboard({
          cleanupSessionData, setQuickPlayActiveSession, setQuickPlaySessionCode, setView, showToast,
        }); }}
        onClassroomClick={() => {
          fetchScores();
          fetchTeacherAssignments();
          setView('classroom');
          // Audit-log the access ONCE per click, not per realtime push.
          // fetchScores re-fires on every progress INSERT, so logging there
          // caused a request storm — see 2026-05-04 audit fix.
          void logAudit('view_gradebook', 'progress');
        }}
        onApprovalsClick={() => { loadPendingStudents(); setView('teacher-approvals'); }}
        onWorksheetResultsClick={activeVoca === 'hebrew' ? undefined : () => setView('worksheet-attempts')}
        onLibraryClick={() => setView('vocabulary-library')}
        onProjectAssignmentToClass={(a) => {
          setActivityNavOrigin(null);
          setClassShowAssignment({ title: a.title, wordIds: a.wordIds, customWords: a.words });
          setView('class-show');
        }}
        onPrintAssignmentWorksheet={(a) => {
          setActivityNavOrigin(null);
          setWorksheetAssignment({ title: a.title, wordIds: a.wordIds, customWords: a.words });
          setView('worksheet');
        }}
        onNewClass={() => setShowCreateClassModal(true)}
        onAssignClass={(c) => startAssignClassFlow(c, {
          setSelectedClass, setView, setAssignmentStep, setSelectedWords,
          setAssignmentTitle, setAssignmentDeadline, setAssignmentModes,
          setAssignmentSentences, setEditingAssignment,
        })}
        onDeleteClass={(classId) => handleDeleteClass(classId)}
        editingClass={editingClass}
        onEditClass={(c) => setEditingClass(c)}
        onCloseEditClass={() => setEditingClass(null)}
        onSaveClassEdit={(next) =>
          editingClass
            ? saveClassEdit(editingClass.id, next, {
                setClasses, showToast,
                onSuccess: () => setEditingClass(null),
              })
            : Promise.resolve()
        }
        onNameChange={(classId, newName) => renameClass(classId, newName, { setClasses, showToast })}
        onAvatarChange={(classId, newAvatar) => changeClassAvatar(classId, newAvatar, { setClasses, showToast })}
        onEditAssignment={(assignment, c) => loadAssignmentIntoCreateForm(assignment, c, false, tdActionDeps)}
        onDuplicateAssignment={(assignment, c) => loadAssignmentIntoCreateForm(assignment, c, true, tdActionDeps)}
        onDeleteAssignment={(assignment) =>
          deleteAssignmentImmediate(assignment.id, {
            setTeacherAssignments, showToast,
            failedDeleteMsg: appToasts.failedDeleteAssignment,
            deletedMsg: appToasts.assignmentDeleted,
          })
        }
        onOpenRoster={(c) => setRosterModalClass(c)}
        savedTasks={savedTasks.tasks}
        onTogglePinSavedTask={savedTasks.togglePin}
        onRemoveSavedTask={savedTasks.remove}
        onUseSavedTask={(task: SavedTask) => applySavedTask(task, {
          allWords, classes, selectedClass,
          savedTasksBumpUse: savedTasks.bumpUse,
          setQuickPlaySelectedWords, setQuickPlayInitialModes,
          setSelectedClass, setSelectedWords,
          setAssignmentTitle, setAssignmentDeadline, setAssignmentModes,
          setAssignmentSentences, setSentenceDifficulty,
          setEditingAssignment, setView, setAssignmentStep,
          showToast,
        })}
        onWizardComplete={(result) =>
          completeTeacherOnboarding(result, {
            user, activeVoca, setClasses, setUser, showToast,
            couldNotSetupClassMsg: appToasts.couldNotSetupClass,
          })
        }
        onWizardSkip={() => skipTeacherOnboarding({ setUser })}
      />
      {rosterModalClass && (
        /* English-subject classes get the redesigned RosterModalV2
           (pastel chrome, kebab actions, frosted code chip).  Hebrew
           classes keep the legacy ClassRosterModal so the VocaHebrew
           dashboard surface stays untouched.  Local Suspense (null
           fallback) so loading the lazy modal chunk doesn't flash the
           full-screen LazyWrapper spinner over the dashboard. */
        <Suspense fallback={null}>
          {(rosterModalClass.subject ?? 'english') === 'english' ? (
            <RosterModalV2
              open={!!rosterModalClass}
              onClose={() => setRosterModalClass(null)}
              classCode={rosterModalClass.code}
              className={rosterModalClass.name}
              classEmoji={rosterModalClass.avatar ?? '🎓'}
            />
          ) : (
            <ClassRosterModal
              open={!!rosterModalClass}
              onClose={() => setRosterModalClass(null)}
              classCode={rosterModalClass.code}
              className={rosterModalClass.name}
            />
          )}
        </Suspense>
      )}
    </LazyWrapper>
  );
}
