/*
 * teacher-resources.ts — copy for the public Resources section.
 *
 * Used by:
 *   - src/components/TeacherResourcesSection.tsx (landing + login)
 *   - LandingPage footer (the new "Teacher PDFs" links)
 *
 * Each PDF link uses the same filename pattern:
 *   /docs/<key>-<lang>.pdf
 * Generated by scripts/teacher-pdfs/build.mjs.
 */

import type { Language } from "../../hooks/useLanguage";

export interface TeacherResourcesStrings {
  sectionEyebrow: string;
  sectionHeading: string;
  sectionSubtitle: string;

  faqCardLabel: string;
  openFaq: string;
  downloadPdf: string;
  downloadInLanguage: string;
  comingSoon: string;

  teacherGuideTitle: string;
  teacherGuideBlurb: string;

  quickStartTitle: string;
  quickStartBlurb: string;

  studentGuideTitle: string;
  studentGuideBlurb: string;

  parentLetterTitle: string;
  parentLetterBlurb: string;

  privacyTitle: string;
  privacyBlurb: string;
  privacyDraftPill: string;

  faqTitle: string;
  faqBlurb: string;
}

const en: TeacherResourcesStrings = {
  sectionEyebrow: "For teachers",
  sectionHeading: "Everything you need to start tomorrow",
  sectionSubtitle:
    "Print, share, or hand out — the essentials for running Vocaband in your classroom, in English, Hebrew, Arabic, and Russian.",
  faqCardLabel: "Open",
  openFaq: "Open FAQ",
  downloadPdf: "Download PDF",
  downloadInLanguage: "Download in",
  comingSoon: "Soon",

  teacherGuideTitle: "Teacher Guide",
  teacherGuideBlurb:
    "The full walk-through — sign in, create a class, build assignments, run Live Challenge, read analytics.",

  quickStartTitle: "Quick Start",
  quickStartBlurb:
    "One page. Five steps. The fastest way to get to your first lesson — perfect for the staffroom wall.",

  studentGuideTitle: "Student Guide",
  studentGuideBlurb:
    "Friendly handout for kids — how to log in with a class code, what to play, why XP and streaks matter.",

  parentLetterTitle: "Parent Letter",
  parentLetterBlurb:
    "A short, printable letter you can send home — explains the app to parents in plain language.",

  privacyTitle: "Privacy & Data",
  privacyBlurb:
    "Plain-English summary for administrators — what we collect, where it lives, how long, who can see it.",
  privacyDraftPill: "DRAFT",

  faqTitle: "FAQ",
  faqBlurb:
    "The questions teachers actually ask — pricing, devices, offline use, data privacy, how to roll out.",
};

const he: TeacherResourcesStrings = {
  sectionEyebrow: "למורות ומורים",
  sectionHeading: "כל מה שצריך כדי להתחיל מחר",
  sectionSubtitle:
    "להדפיס, לשתף או לחלק — האסנטיאלס להפעלת Vocaband בכיתה, בעברית, ערבית, אנגלית ורוסית.",
  faqCardLabel: "פתחו",
  openFaq: "פתחו שאלות נפוצות",
  downloadPdf: "הורידו PDF",
  downloadInLanguage: "הורדה בשפה",
  comingSoon: "בקרוב",

  teacherGuideTitle: "מדריך למורה",
  teacherGuideBlurb:
    "סקירה מלאה — התחברות, יצירת כיתה, בניית מטלות, אתגר חי וקריאת נתונים.",

  quickStartTitle: "מדריך מהיר",
  quickStartBlurb:
    "עמוד אחד, חמישה שלבים. הדרך המהירה ביותר לשיעור הראשון — מצוין לקיר חדר המורים.",

  studentGuideTitle: "מדריך לתלמיד",
  studentGuideBlurb:
    "דף חברותי לילדים — איך נכנסים עם קוד כיתה, מה לעשות, למה XP ורצף חשובים.",

  parentLetterTitle: "מכתב להורים",
  parentLetterBlurb:
    "מכתב קצר להדפסה ולחלוקה — מסביר להורים בשפה פשוטה במה מדובר.",

  privacyTitle: "פרטיות ונתונים",
  privacyBlurb:
    "סיכום ברור להנהלה — מה אנחנו אוספים, איפה זה נשמר, כמה זמן, ומי רואה.",
  privacyDraftPill: "טיוטה",

  faqTitle: "שאלות נפוצות",
  faqBlurb:
    "השאלות שמורים באמת שואלים — מחיר, מכשירים, אופליין, פרטיות וכניסה לבית הספר.",
};

const ar: TeacherResourcesStrings = {
  sectionEyebrow: "للمعلمين",
  sectionHeading: "كل ما تحتاجه لتبدأ غداً",
  sectionSubtitle:
    "اطبع، شارك أو وزّع — الأساسيات لتشغيل Vocaband في صفك، بالعربية والعبرية والإنجليزية والروسية.",
  faqCardLabel: "افتح",
  openFaq: "افتح الأسئلة الشائعة",
  downloadPdf: "حمّل PDF",
  downloadInLanguage: "حمّل بـ",
  comingSoon: "قريباً",

  teacherGuideTitle: "دليل المعلم",
  teacherGuideBlurb:
    "الجولة الكاملة — تسجيل الدخول، إنشاء الصف، بناء المهام، التحدي المباشر وقراءة التحليلات.",

  quickStartTitle: "بداية سريعة",
  quickStartBlurb:
    "صفحة واحدة، خمس خطوات. أسرع طريق إلى أول حصة — مثالي لحائط غرفة المعلمين.",

  studentGuideTitle: "دليل الطالب",
  studentGuideBlurb:
    "ورقة ودودة للأطفال — كيف يدخلون برمز الصف، ماذا يلعبون، ولماذا XP والسلسلة مهمتان.",

  parentLetterTitle: "رسالة للأهل",
  parentLetterBlurb:
    "رسالة قصيرة قابلة للطباعة ترسلها إلى البيت — تشرح للأهل بلغة بسيطة.",

  privacyTitle: "الخصوصية والبيانات",
  privacyBlurb:
    "ملخّص واضح للإدارة — ماذا نجمع، أين يُخزَّن، كم يبقى، ومن يصل إليه.",
  privacyDraftPill: "مسودة",

  faqTitle: "الأسئلة الشائعة",
  faqBlurb:
    "الأسئلة التي يطرحها المعلمون فعلاً — السعر، الأجهزة، العمل بدون إنترنت، الخصوصية والنشر في المدرسة.",
};

export const teacherResourcesT: Record<Language, TeacherResourcesStrings> = { en, he, ar };
