/*
 * teacher-resources.ts — copy for the public Resources section.
 *
 * Used by:
 *   - src/components/TeacherResourcesSection.tsx (landing + login)
 *   - LandingPage footer (the new "Teacher PDFs" links)
 *
 * Each PDF link uses the same filename pattern:
 *   /docs/<key>-<lang>.pdf
 * Generated by scripts/teacher-pdfs/build.mjs.
 */

import type { Language } from "../../hooks/useLanguage";

export interface TeacherResourcesStrings {
  sectionEyebrow: string;
  sectionHeading: string;
  sectionSubtitle: string;

  downloadPdf: string;
  downloadInLanguage: string;
  comingSoon: string;
  recommendedPill: string;
  previewLabel: string;

  schoolGroupHeading: string;
  teacherGroupHeading: string;

  schoolPitchTitle: string;
  schoolPitchBlurb: string;

  teacherGuideTitle: string;
  teacherGuideBlurb: string;

  quickStartTitle: string;
  quickStartBlurb: string;

  studentGuideTitle: string;
  studentGuideBlurb: string;

  parentLetterTitle: string;
  parentLetterBlurb: string;
}

const en: TeacherResourcesStrings = {
  sectionEyebrow: "For teachers",
  sectionHeading: "Everything you need to start tomorrow",
  sectionSubtitle:
    "Print, share, or hand out — the essentials for running Vocaband in your classroom, in English, Hebrew, Arabic, and Russian.",
  downloadPdf: "Download PDF",
  downloadInLanguage: "Download",
  comingSoon: "Soon",
  recommendedPill: "Recommended",
  previewLabel: "Preview",

  schoolGroupHeading: "For schools",
  teacherGroupHeading: "For teachers",

  schoolPitchTitle: "School Pitch Deck",
  schoolPitchBlurb:
    "A printable slide deck for principal meetings — what students learn, how rollout works, pricing, and a privacy summary.",

  teacherGuideTitle: "Teacher Guide",
  teacherGuideBlurb:
    "The full walk-through — sign in, create a class, build assignments, run Live Challenge, read analytics.",

  quickStartTitle: "Quick Start",
  quickStartBlurb:
    "One page. Five steps. The fastest way to get to your first lesson — perfect for the staffroom wall.",

  studentGuideTitle: "Student Guide",
  studentGuideBlurb:
    "Friendly handout for kids — how to log in with a class code, what to play, why XP and streaks matter.",

  parentLetterTitle: "Parent Letter",
  parentLetterBlurb:
    "A short, printable letter you can send home — explains the app to parents in plain language.",
};

const he: TeacherResourcesStrings = {
  sectionEyebrow: "למורות ומורים",
  sectionHeading: "כל מה שצריך כדי להתחיל מחר",
  sectionSubtitle:
    "להדפיס, לשתף או לחלק — האסנטיאלס להפעלת Vocaband בכיתה, בעברית, ערבית, אנגלית ורוסית.",
  downloadPdf: "הורידו PDF",
  downloadInLanguage: "הורדה",
  comingSoon: "בקרוב",
  recommendedPill: "מומלץ",
  previewLabel: "תצוגה",

  schoolGroupHeading: "לבתי ספר",
  teacherGroupHeading: "למורות ומורים",

  schoolPitchTitle: "מצגת לבית הספר",
  schoolPitchBlurb:
    "מצגת להדפסה לפגישה עם המנהל/ת — מה התלמידים לומדים, איך מיישמים, תמחור וסיכום פרטיות.",

  teacherGuideTitle: "מדריך למורה",
  teacherGuideBlurb:
    "סקירה מלאה — התחברות, יצירת כיתה, בניית מטלות, אתגר חי וקריאת נתונים.",

  quickStartTitle: "מדריך מהיר",
  quickStartBlurb:
    "עמוד אחד, חמישה שלבים. הדרך המהירה ביותר לשיעור הראשון — מצוין לקיר חדר המורים.",

  studentGuideTitle: "מדריך לתלמיד",
  studentGuideBlurb:
    "דף חברותי לילדים — איך נכנסים עם קוד כיתה, מה לעשות, למה XP ורצף חשובים.",

  parentLetterTitle: "מכתב להורים",
  parentLetterBlurb:
    "מכתב קצר להדפסה ולחלוקה — מסביר להורים בשפה פשוטה במה מדובר.",
};

const ar: TeacherResourcesStrings = {
  sectionEyebrow: "للمعلمين",
  sectionHeading: "كل ما تحتاجه لتبدأ غداً",
  sectionSubtitle:
    "اطبع، شارك أو وزّع — الأساسيات لتشغيل Vocaband في صفك، بالعربية والعبرية والإنجليزية والروسية.",
  downloadPdf: "حمّل PDF",
  downloadInLanguage: "تحميل",
  comingSoon: "قريباً",
  recommendedPill: "موصى به",
  previewLabel: "معاينة",

  schoolGroupHeading: "للمدارس",
  teacherGroupHeading: "للمعلمين",

  schoolPitchTitle: "عرض تقديمي للمدرسة",
  schoolPitchBlurb:
    "عرض شرائح للطباعة لاجتماعات الإدارة — ماذا يتعلّم الطلاب، كيف يتمّ التطبيق، الأسعار وموجز الخصوصية.",

  teacherGuideTitle: "دليل المعلم",
  teacherGuideBlurb:
    "الجولة الكاملة — تسجيل الدخول، إنشاء الصف، بناء المهام، التحدي المباشر وقراءة التحليلات.",

  quickStartTitle: "بداية سريعة",
  quickStartBlurb:
    "صفحة واحدة، خمس خطوات. أسرع طريق إلى أول حصة — مثالي لحائط غرفة المعلمين.",

  studentGuideTitle: "دليل الطالب",
  studentGuideBlurb:
    "ورقة ودودة للأطفال — كيف يدخلون برمز الصف، ماذا يلعبون، ولماذا XP والسلسلة مهمتان.",

  parentLetterTitle: "رسالة للأهل",
  parentLetterBlurb:
    "رسالة قصيرة قابلة للطباعة ترسلها إلى البيت — تشرح للأهل بلغة بسيطة.",
};

export const teacherResourcesT: Record<Language, TeacherResourcesStrings> = { en, he, ar };
