/**
 * FillBlankExercise — show a sentence with the target word replaced
 * by a blank; the student types the missing word.
 *
 * Sentences come from src/data/sentence-bank-fillblank.ts which is
 * generated by scripts/generate-fillblank-sentences.ts.  Words without
 * a sentence in the bank are skipped at mount time — better than
 * showing a blank-only sentence or a synthetic template.
 *
 * Score model: one point per correct first submission.
 */
import { useEffect, useMemo, useState } from "react";
import { motion } from "motion/react";
import { Volume2 } from "lucide-react";
import { useAudio } from "../../hooks/useAudio";
import { FILLBLANK_SENTENCES } from "../../data/sentence-bank-fillblank";
import type { Answer, ExerciseComponent, ExerciseOf } from "../types";
import { normaliseAnswer, shuffle } from "../shared";

type Item = { word_id: number; english: string; sentence: string; blanked: string };

// "He admit"  →  "He ____"  with the actual word swapped for an
// underscore run.  Falls back to a plain underscore run if the word
// isn't found (which only happens if the bank drifts from vocabulary).
const blankOut = (sentence: string, word: string): string => {
  const re = new RegExp(`\\b${word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i");
  return sentence.replace(re, "_".repeat(Math.max(4, word.length)));
};

export const FillBlankExercise: ExerciseComponent<ExerciseOf<"fill_blank">> = ({
  words,
  onComplete,
}) => {
  const { speak } = useAudio();
  const items: Item[] = useMemo(
    () =>
      words
        .map((w) => {
          const sentence = FILLBLANK_SENTENCES.get(w.id);
          if (!sentence) return null;
          return {
            word_id: w.id,
            english: w.english,
            sentence,
            blanked: blankOut(sentence, w.english),
          };
        })
        .filter((x): x is Item => x !== null),
    [words],
  );

  const [order] = useState(() => shuffle(items));
  const [idx, setIdx] = useState(0);
  const [typed, setTyped] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [correct, setCorrect] = useState(0);
  const [answers, setAnswers] = useState<Answer[]>([]);

  useEffect(() => {
    if (order.length === 0) {
      onComplete({ score: 0, total: 0, answers: [] });
    }
  }, [order.length, onComplete]);

  if (order.length === 0) return null;
  const current = order[idx];
  if (!current) return null;

  const isRight = !!typed && normaliseAnswer(typed) === normaliseAnswer(current.english);

  const handleSubmit = () => {
    if (submitted || !typed.trim()) return;
    setSubmitted(true);
    if (isRight) setCorrect((c) => c + 1);

    const answer: Answer = {
      kind: "fill_blank",
      word_id: current.word_id,
      sentence: current.sentence,
      typed,
      is_correct: isRight,
    };
    const nextAnswers = [...answers, answer];
    setAnswers(nextAnswers);

    setTimeout(() => {
      if (idx + 1 < order.length) {
        setIdx(idx + 1);
        setTyped("");
        setSubmitted(false);
      } else {
        const finalScore = correct + (isRight ? 1 : 0);
        onComplete({ score: finalScore, total: order.length, answers: nextAnswers });
      }
    }, 1100);
  };

  const playAudio = () => {
    speak(current.word_id, current.english);
  };

  return (
    <div className="bg-white rounded-3xl p-6 sm:p-8 shadow-2xl">
      <div className="flex items-center justify-between mb-6">
        <span className="text-xs font-bold text-stone-500">
          {idx + 1} / {order.length}
        </span>
        <span className="text-xs font-bold text-emerald-600">{correct} correct</span>
      </div>

      <p className="text-xs uppercase tracking-widest font-bold text-stone-400 mb-3 text-center">
        Fill in the blank
      </p>

      <motion.div
        key={idx}
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        className="rounded-2xl bg-gradient-to-br from-violet-50 to-fuchsia-50 border border-violet-100 px-5 py-6 mb-5 text-center"
      >
        <p className="text-xl sm:text-2xl font-bold text-stone-800 leading-relaxed" dir="ltr">
          {current.blanked}
        </p>
      </motion.div>

      <form
        onSubmit={(e) => {
          e.preventDefault();
          handleSubmit();
        }}
      >
        <input
          type="text"
          value={typed}
          onChange={(e) => setTyped(e.target.value)}
          disabled={submitted}
          placeholder="Type the missing word"
          autoComplete="off"
          autoCapitalize="off"
          spellCheck={false}
          className={`w-full px-4 py-3 rounded-xl border-2 font-bold text-lg text-center transition-all ${
            !submitted
              ? "border-stone-200 focus:border-violet-500 focus:outline-none text-stone-900"
              : isRight
                ? "border-emerald-500 bg-emerald-50 text-emerald-900"
                : "border-rose-500 bg-rose-50 text-rose-900"
          }`}
          dir="ltr"
        />
        {submitted && !isRight && (
          <p className="text-center text-sm font-bold text-rose-700 mt-3">
            Answer: <span className="text-rose-900">{current.english}</span>
          </p>
        )}
        <div className="mt-4 flex items-center justify-between gap-2">
          <button
            type="button"
            onClick={playAudio}
            className="text-xs font-bold text-stone-500 hover:text-stone-700 inline-flex items-center gap-1"
          >
            <Volume2 size={12} /> Hear the word
          </button>
          <button
            type="submit"
            disabled={submitted || !typed.trim()}
            className="px-5 py-2.5 rounded-xl bg-violet-500 hover:bg-violet-600 disabled:opacity-40 disabled:cursor-not-allowed text-white font-bold transition-all"
            style={{ touchAction: "manipulation", WebkitTapHighlightColor: "transparent" }}
          >
            Submit
          </button>
        </div>
      </form>
    </div>
  );
};

export default FillBlankExercise;
