/**
 * Phase 2: Remove duplicate English entries.
 *
 * Input:  tmp/vocabulary-01-cleaned.ts
 * Output: tmp/vocabulary-02-deduped.ts + tmp/report-02-deduped.txt
 *
 * Dedup key: lowercased + whitespace-collapsed English. Two entries that
 * differ only in case or spacing are considered the same word.
 *
 * Merge strategy — when duplicates are found:
 *   1. Prefer the entry with BOTH Hebrew AND Arabic filled
 *   2. If tied, prefer the one with longer translations (more detail)
 *   3. If still tied, keep the one with the lowest ID (original)
 *
 * IDs: we keep the winner's ID. Losing IDs are logged so a manual
 * progress-record migration can reassign them if needed.
 */
import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import type { Word } from '../../src/data/vocabulary'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const OUTPUT_DIR = path.join(__dirname, '../../tmp')

async function loadPhase1(): Promise<Word[]> {
  const phase1Path = path.join(OUTPUT_DIR, 'vocabulary-01-cleaned.ts')
  if (!fs.existsSync(phase1Path)) {
    throw new Error('Run scripts/vocab-cleanup/01-strip-parens.ts first — phase 1 output missing.')
  }
  const mod = await import(phase1Path)
  return mod.ALL_WORDS as Word[]
}

function normKey(text: string): string {
  return text.toLowerCase().replace(/\s+/g, ' ').trim()
}

function score(word: Word): number {
  const hasHebrew = !!word.hebrew?.trim()
  const hasArabic = !!word.arabic?.trim()
  const both = hasHebrew && hasArabic ? 1000 : 0
  const len = (word.hebrew?.length ?? 0) + (word.arabic?.length ?? 0)
  return both + len
}

const run = async () => {
  const words = await loadPhase1()
  const byKey = new Map<string, Word[]>()
  for (const w of words) {
    const k = normKey(w.english)
    if (!byKey.has(k)) byKey.set(k, [])
    byKey.get(k)!.push(w)
  }

  const deduped: Word[] = []
  const duplicateReports: { kept: Word; dropped: Word[] }[] = []

  for (const [, group] of byKey) {
    if (group.length === 1) {
      deduped.push(group[0])
      continue
    }
    // Score each, keep best. Break ties by lowest ID.
    group.sort((a, b) => {
      const s = score(b) - score(a)
      return s !== 0 ? s : a.id - b.id
    })
    const kept = group[0]
    const dropped = group.slice(1)
    deduped.push(kept)
    duplicateReports.push({ kept, dropped })
  }

  // Sort by ID for stable output
  deduped.sort((a, b) => a.id - b.id)

  const outPath = path.join(OUTPUT_DIR, 'vocabulary-02-deduped.ts')
  const header = `// Auto-generated by scripts/vocab-cleanup/02-dedupe.ts\n// Phase 2: Duplicates merged (best translations kept).\n\nimport type { Word } from '../src/data/vocabulary'\n\nexport const ALL_WORDS: Word[] = `
  fs.writeFileSync(outPath, header + JSON.stringify(deduped, null, 2) + '\n')

  const reportPath = path.join(OUTPUT_DIR, 'report-02-deduped.txt')
  const lines: string[] = []
  lines.push(`Phase 2 — Deduplication`)
  lines.push(`========================\n`)
  lines.push(`Input: ${words.length} words`)
  lines.push(`Unique keys: ${byKey.size}`)
  lines.push(`Duplicates found: ${words.length - byKey.size}`)
  lines.push(`Output: ${deduped.length} words\n`)
  if (duplicateReports.length > 0) {
    lines.push(`--- Duplicates merged (first 30) ---`)
    duplicateReports.slice(0, 30).forEach(({ kept, dropped }) => {
      lines.push(`\n  KEPT  ${kept.id}: "${kept.english}" he="${kept.hebrew}" ar="${kept.arabic}"`)
      dropped.forEach(d => {
        lines.push(`  DROP  ${d.id}: "${d.english}" he="${d.hebrew}" ar="${d.arabic}"`)
      })
    })
    if (duplicateReports.length > 30) {
      lines.push(`\n  ... and ${duplicateReports.length - 30} more duplicate groups`)
    }
  }
  fs.writeFileSync(reportPath, lines.join('\n'))

  console.log(`✅ Phase 2 complete`)
  console.log(`   Duplicates merged: ${words.length - byKey.size}`)
  console.log(`   Output: ${deduped.length} unique words → tmp/vocabulary-02-deduped.ts`)
  console.log(`   Report: tmp/report-02-deduped.txt`)
}

run().catch(err => { console.error(err); process.exit(1) })
