// AUTO-GENERATED by scripts/generate-fillblank-sentences.ts.
// Re-run that script (with GOOGLE_AI_API_KEY set) to refresh.
//
// Source of truth for fill-in-the-blank sentences in Free Resources.
// Each entry is one EFL-friendly sentence (5-10 words) that literally
// contains the target word, validated at generation time.
//
// Stub file: contains zero entries until the generation script is run
// locally. The Free Resources fill-blank generator falls back to the
// existing sentence-bank.ts logic for any missing IDs.

export const FILLBLANK_SENTENCES = new Map<number, string>([]);
