// Auto-generated by scripts/translate-vocabulary-to-russian.ts.
// Do not hand-edit — re-run the script to update.
//
// Maps vocabulary word id → Russian translation.  vocabulary.ts
// hydrates ALL_WORDS[i].russian from this map at module load.
//
// Empty stub until the translator script is run with a Gemini key:
//   GOOGLE_CLOUD_API_KEY=… npx tsx scripts/translate-vocabulary-to-russian.ts

export const RUSSIAN_TRANSLATIONS: Record<number, string> = {};
