// AUTO-GENERATED by scripts/generate-word-definitions.ts.
// Re-run that script (with GOOGLE_AI_API_KEY set) to populate.
//
// Source of truth for EFL-friendly word definitions consumed by the
// Definition Match interactive worksheet exercise.  Each entry is
// 3-12 words, doesn't repeat the target word, validated at generation
// time.  This file ships empty so the exercise compiles and degrades
// gracefully — running the script fills it in.

export const WORD_DEFINITIONS = new Map<number, string>([]);
